CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    country    VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(50)                             NOT NULL DEFAULT 'CUSTOMER',
    dob        DATE                                    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE TABLE IF NOT EXISTS specialist_profiles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    description        VARCHAR(1000),
    experience_years   INTEGER,
    education          VARCHAR(255),
    hourly_rate        DECIMAL(10, 2),
    fixed_price        DECIMAL(10, 2),
    service_area       VARCHAR(255),
    is_verified        BOOLEAN                                 NOT NULL DEFAULT FALSE,
    moderation_status  VARCHAR(50)                             NOT NULL DEFAULT 'PENDING',
    average_rating     DECIMAL(3, 2)                           NOT NULL DEFAULT 0.0,
    CONSTRAINT pk_specialist_profiles PRIMARY KEY (id)
);

ALTER TABLE specialist_profiles
    ADD CONSTRAINT fk_specialist_profiles_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- Уникальность: один пользователь - один профиль специалиста
ALTER TABLE specialist_profiles
    ADD CONSTRAINT uc_specialist_profiles_user UNIQUE (user_id);

-- 3. Таблица категорий специалистов
CREATE TABLE IF NOT EXISTS specialist_categories
(
    specialist_id BIGINT       NOT NULL,
    category      VARCHAR(255) NOT NULL,
    CONSTRAINT pk_specialist_categories PRIMARY KEY (specialist_id, category),
    CONSTRAINT fk_specialist_categories_profile
        FOREIGN KEY (specialist_id) REFERENCES specialist_profiles(id) ON DELETE CASCADE
);

-- Индекс для поиска по категориям
CREATE INDEX idx_specialist_categories_category ON specialist_categories(category);

CREATE TABLE specialist_categories
(
    specialist_id BIGINT       NOT NULL,
    category      VARCHAR(255) NOT NULL,
    CONSTRAINT pk_specialist_categories PRIMARY KEY (specialist_id, category),
    CONSTRAINT fk_specialist_categories_specialist FOREIGN KEY (specialist_id) REFERENCES specialist_profiles(id) ON DELETE CASCADE
);

-- Таблица портфолио
CREATE TABLE portfolio_items
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    specialist_id  BIGINT                                  NOT NULL,
    title          VARCHAR(255),
    description    VARCHAR(500),
    image_url      VARCHAR(255),
    created_at     TIMESTAMP,
    CONSTRAINT pk_portfolio_items PRIMARY KEY (id)
);

ALTER TABLE portfolio_items
    ADD CONSTRAINT fk_portfolio_items_specialist FOREIGN KEY (specialist_id) REFERENCES specialist_profiles(id) ON DELETE CASCADE;

-- Таблица заказов
CREATE TABLE orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id    BIGINT                                  NOT NULL,
    specialist_id  BIGINT,
    description    VARCHAR(2000)                           NOT NULL,
    address        VARCHAR(255),
    budget         DECIMAL(10, 2),
    deadline       TIMESTAMP,
    status         VARCHAR(50)                             NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_specialist FOREIGN KEY (specialist_id) REFERENCES users(id) ON DELETE SET NULL;

-- Таблица заявок
CREATE TABLE bids
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id       BIGINT                                  NOT NULL,
    specialist_id  BIGINT                                  NOT NULL,
    price          DECIMAL(10, 2),
    comment        VARCHAR(500),
    created_at     TIMESTAMP,
    is_selected    BOOLEAN                                 NOT NULL DEFAULT false,
    CONSTRAINT pk_bids PRIMARY KEY (id)
);

ALTER TABLE bids
    ADD CONSTRAINT fk_bids_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;

ALTER TABLE bids
    ADD CONSTRAINT fk_bids_specialist FOREIGN KEY (specialist_id) REFERENCES users(id) ON DELETE CASCADE;

-- Уникальное ограничение: специалист не может оставить более одной заявки на один заказ
ALTER TABLE bids
    ADD CONSTRAINT uc_bids_order_specialist UNIQUE (order_id, specialist_id);

-- Таблица отзывов
CREATE TABLE reviews
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id           BIGINT                                  NOT NULL,
    customer_id        BIGINT                                  NOT NULL,
    specialist_id      BIGINT                                  NOT NULL,
    rating             INTEGER,
    comment            VARCHAR(1000),
    parent_review_id   BIGINT,
    status             VARCHAR(50)                             NOT NULL DEFAULT 'PENDING',
    moderation_reason  VARCHAR(255),
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

ALTER TABLE reviews
    ADD CONSTRAINT fk_reviews_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;

ALTER TABLE reviews
    ADD CONSTRAINT fk_reviews_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE reviews
    ADD CONSTRAINT fk_reviews_specialist FOREIGN KEY (specialist_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE reviews
    ADD CONSTRAINT fk_reviews_parent FOREIGN KEY (parent_review_id) REFERENCES reviews(id) ON DELETE CASCADE;

-- Проверка рейтинга (1-5)
ALTER TABLE reviews
    ADD CONSTRAINT chk_reviews_rating CHECK (rating >= 1 AND rating <= 5);

-- Уникальное ограничение: один заказчик может оставить только один отзыв на специалиста
ALTER TABLE reviews
    ADD CONSTRAINT uc_reviews_customer_specialist UNIQUE (customer_id, specialist_id);

-- Индексы для улучшения производительности
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);

CREATE INDEX idx_specialist_profiles_moderation_status ON specialist_profiles(moderation_status);
CREATE INDEX idx_specialist_profiles_is_verified ON specialist_profiles(is_verified);
CREATE INDEX idx_specialist_profiles_average_rating ON specialist_profiles(average_rating);

CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_specialist_id ON orders(specialist_id);
CREATE INDEX idx_orders_created_at ON orders(created_at);

CREATE INDEX idx_bids_order_id ON bids(order_id);
CREATE INDEX idx_bids_specialist_id ON bids(specialist_id);
CREATE INDEX idx_bids_is_selected ON bids(is_selected);

CREATE INDEX idx_reviews_specialist_id ON reviews(specialist_id);
CREATE INDEX idx_reviews_status ON reviews(status);
CREATE INDEX idx_reviews_rating ON reviews(rating);
CREATE INDEX idx_reviews_created_at ON reviews(created_at);